version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map the container's port 8000 to the host's port 8000 (you can change this as needed)
    volumes:
      - .:/app
