# Generated by Django 4.2.2 on 2023-06-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_audiofile_delete_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=1)),
                ('transcript', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
